// <auto-generated />
using QemmaProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QemmaProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721120000_AddFantasyTransfersAndPlayerProfiles")]
    partial class AddFantasyTransfersAndPlayerProfiles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");
#pragma warning restore 612, 618
        }
    }
}
